### ISSUE TITLE
CircleCI: Pipeline fails on "plugin:ci-build --backend win64"

### ISSUE THREAD

**Issue by amotl** [panodata/grafana-worldmap-panel#16]
Dear @ryantxu and @dprokop,

while working on #8 and after integrating Ryan's changes into the "develop" branch, the CircleCI pipeline fails when using the `--backend win64` option [1].

The error we are getting is
```
npx grafana-toolkit plugin:ci-build --backend win64
Invalid argument: win64
```

We tried some things but we are now really out of ideas what was the reason this broke down. Please recognize we moved from the "hiveeyes" organization to "panodata". However, the transition looks good in general so far [2].

Maybe you have some idea what might be causing this? We would like to continue working on the codebase and look forward to using CircleCI for generating installable packages.

Thanks in advance and with kind regards,
Andreas.

[1] https://circleci.com/gh/panodata/grafana-worldmap-panel/72
[2] https://circleci.com/gh/panodata/grafana-worldmap-panel

**Comment by amotl** [comment]
Within https://github.com/panodata/grafana-worldmap-panel/tree/circleci-2.1, we removed the checks on win64 and macosx. After doing so, we are running into #14 again.

**Comment by ryantxu** [comment]
You can remove all of the "backend" tasks -- they were really just for testing :(

I'll comment on #14 directly

**Comment by amotl** [comment]
Thanks. We just amended the "develop" branch accordingly.
