### ISSUE TITLE
Map not rendering correctly in 6.3

### ISSUE THREAD

**Issue by code4me-xx** [panodata/grafana-worldmap-panel#17]
Hi,

I've just tried this panel and like it very much, but I realized that it have the same rendering problem as the ordinary worldmap on Grafana >= 6.3.

The fix is to use a low refresh interval, but they actually solved it.

https://github.com/grafana/worldmap-panel/issues/212

Regards Peter

**Comment by amotl** [comment]
Dear @code4me-xx,

the respective fix by @torkelo for mitigating the rendering woes should already have landed here through https://github.com/panodata/grafana-worldmap-panel/commit/f6521000c310bc74230440ffc64d8a02bca186fe, see also https://github.com/grafana/worldmap-panel/issues/213. Thanks for downstreaming this, @ryantxu!

However, we have not been able release an installeable artifact yet, so you should try to build from source in order to get that.

We will be happy to hear about the outcome.

Cheers,
Andreas.

**Comment by code4me-xx** [comment]
Hi Andreas,

Thank you for the prompt response :-)

I've tried to build from source but it fails on 'npm run build' with:

`  ERROR in /home/mint/go/src/github.com/grafana/grafana/data/plugins/grafana-worldmap-panel/src/core.ts
  [tsl] ERROR in /home/mint/go/src/github.com/grafana/grafana/data/plugins/grafana-worldmap-panel/src/core.ts(54,17)
        TS2339: Property 'url' does not exist on type 'JQueryXHR'
`

Regards Peter

**Comment by amotl** [comment]
Hi Peter,

invoking `yarn install` and then `yarn build` recently worked for us, see also #8. Please let us know about your outcome.

With kind regards,
Andreas.

**Comment by code4me-xx** [comment]
Hi Andreas,

I deleted everything and started over, making sure it was the development branch. Using `yarn install` and `yarn build` gives the same error.

Building Grafana and plugins from source is quite new for me so there might be something wrong with the tool chain, but Grafana is building and running fine using this guide https://grafana.com/docs/v6.2/project/building_from_source/ 

I'm trying to follow the steps in CONTRIBUTING.md, but is that wrong?

Regards Peter

**Comment by amotl** [comment]
Dear Peter,

sorry to hear that building from source doesn't work for you out of the box. I just tried to repeat the process of building from source and can confirm it works for us.
```
git clone https://github.com/panodata/grafana-worldmap-panel
cd grafana-worldmap-panel
yarn install
yarn build
```

Then, you would symlink the `dist/` folder into the Grafana `plugins` directory, which is `/var/lib/grafana/plugins` on Linux and `/usr/local/var/lib/grafana/plugins` on macOS/Homebrew.

While I can't say anything about the contents of `CONTRIBUTING.md` being outdated, we are using `yarn` over here which works pretty well for us.

With kind regards,
Andreas.

**Comment by code4me-xx** [comment]
Hi Andreas,

I've made a fresh Linux with only git and yarn, and was able to build the plugin. I tried to use the panel on a development server but the name is apparently the same as the original map.

I'll try again after the weekend.

Regards Peter

**Comment by code4me-xx** [comment]
Hi Andreas,

I've managed to build and deploy the source, but it isn't rendering correctly. It is better and display a map, but it isn't using the entire panel before the refresh timer kicks in (See examples below).

![image](https://user-images.githubusercontent.com/1695378/66287879-8f38fc80-e8d7-11e9-88bd-21db1322a402.png)

![image](https://user-images.githubusercontent.com/1695378/66287910-b1327f00-e8d7-11e9-90d7-dacf3dcc9523.png)

Regards Peter

**Comment by amotl** [comment]
Dear Peter,

thanks for the update. I've experienced the behavior you are observing a few times during development of the Worldmap Panel improvements. Hoping that the current thing would still work on Grafana 6.3, there  seem to have been some updates on Grafana 6.4 which influence the timing behavior obviously in the same way I've recognized before.

With kind regards,
Andreas.

**Comment by amotl** [comment]
Hi there,

looks like Grafana 6.4.2 makes things work again, see https://github.com/grafana/worldmap-panel/issues/223.

Cheers,
Andreas.

**Comment by amotl** [comment]
Dear Peter,

are you able to confirm this starts working for you when using Grafana >6.4.2 again?

With kind regards,
Andreas.

**Comment by code4me-xx** [comment]
Hi Andreas,

Yes it works. Thank you.

Regards Peter

**Comment by amotl** [comment]
Thanks!
